spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./rental'
  jpa:
    generate-ddl: true
    hibernate-ddl-auto: validate
task.template.allowMultipleTasks: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
